# -*- coding: utf-8 -*-
"""machine learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxokWyuv4DGWBNIlfUcTj320oGxdix8x
"""

import numpy as np
from sklearn import linear_model
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from sklearn.datasets import load_boston
boston=load_boston()
#print(boston)

x=pd.DataFrame(boston.data,columns=boston.feature_names)
y=pd.DataFrame(boston.target)

regration=linear_model.LinearRegression()
print(regration)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1,random_state=42)



regration.fit(x_train,y_train)

#print(regration.coef_)

y_predict=regration.predict(x_test)
#print(y_predict)

#print(y_test)

accuracy=np.mean((y_predict-y_test)**2)
print(accuracy)